### ISSUE TITLE
Can't use this tool.

### ISSUE THREAD

**Issue by lvdaqian** [blakeembrey/node-module-template#6]
When start to generate a new module, only LICENSE file was generated. No other files.

I guess there must be something missing in the package.json. So the template files were not installed into the system.

logs below:
Creating module...

Writing "/Users/darwin/code/Demo/log-analyzer/log-analyzer/LICENSE" to filesystem...

Module created!

**Comment by blakeembrey** [comment]
@lvdaqian You're right, let me quickly fix that for you. That might be the dumbest thing I've done in a while :+1:

**Comment by blakeembrey** [comment]
I'm having trouble adding the hidden files for NPM. I just sent them a message and if that fails I'll make a manual file map and remove the hidden files so they can be published. Let me know if you have an idea to solve this too, as I tried the empty `.npmignore` and adding the `files` array with hidden files and neither worked :smile:

**Comment by lvdaqian** [comment]
@blakeembrey  You response is so quick. Thank you. 
I just got an idea. Why do you rename the files in the source with a special format. 
For example. `_TEMPLATE_package.json`, `_TEMPLATE_.gitignore`
And just remove the `_TEMPLATE_`from the filename before call `writeFile`.

**Comment by blakeembrey** [comment]
Yeah, I was thinking the same :+1: If there's no response when I wake up in the morning, I'll probably go that route.

**Comment by blakeembrey** [comment]
@lvdaqian Thanks for the prefix idea! I went with just a single `_` as it looks pretty clean and it works great. Give it a go now for me :smile:
